### PR TITLE
Add get_residual(); update example

### PR DESCRIPTION
**Pull request by kfeng19**
Added the helper function get_residual(). Some minor updates in the example file to use the function.

### CODE REVIEW

**Comment by chaaland** [comment]
I think this might function might be better off residing is user code. The residual defined here only makes sense for the least squares case right? The cost in the orthogonal distance case is the squared euclidean distance between two points. Think it'd be better left to the user to define their own residual that makes sense for their use case. Thoughts?

**Comment by kfeng19** [comment]
OK for me. Just curious, how would you define the residual for the orthogonal distance?

**Comment by chaaland** [comment]
The orthogonal distance would have residual equal to the norm square of the distance between the data point and the closest point on the fitted ellipse

**Comment by kfeng19** [comment]
OK thanks. 
I think I'll just stick with this function for both methods -- the result looks reasonable and catches the different "bad points" for the two methods respectively.

**Pull request closed without merging**
